### ISSUE TITLE
Create some documentation

### ISSUE THREAD

**Issue by R0kkxSynetique** [CPNV-RIA1/planes-store#16]
## Description
It's important to create some documents that represent multiple things needed for the project and the thought about it.

## ToDo
- [x] Create the workflow of the project (How everything works together).
- [x] Create the architecture of the project (Structure).
- [x] Create the layers of the application and its job.
- [x] Update the class diagram.
